const nodemailer = require("nodemailer");

const { getTransactionalTemplate } = require("./utils/mail-template-chrome");

const sendTransactionalEmail = async emailData => {
  if (process.env.NODE_ENV === "production") {
    // create Nodemailer SES transporter
    let transporter = nodemailer.createTransport({
      port: 465,
      host: "email-smtp.us-west-2.amazonaws.com",
      secure: true,
      auth: {
        user: process.env.AWS_SES_SMTP_USER,
        pass: process.env.AWS_SES_SMTP_PASSWORD
      },
      sendingRate: 1 // max 1 messages/second
    });

    const mailOptions = {
      from: "no-reply@4-playersofcolorado.org", // default
      ...emailData,
      subject: `[4-Players] ${emailData.subject}`,
      html: getTransactionalTemplate(
        emailData.preheader || emailData.subject,
        emailData.subject,
        emailData.html
      )
    };

    // send some mail
    return transporter.sendMail(mailOptions, (err, info) => {
      if (err) {
        throw new Error(err);
      }

      const msg = "Message sent";
      console.log(`${msg}: ${info.messageId}`);
      return Promise.resolve(msg);
    });
  } else {
    const transport = nodemailer.createTransport({
      host: "smtp.mailtrap.io",
      port: 2525,
      auth: {
        user: "00abda4abf8551", //generated by Mailtrap
        pass: "82046488050e87" //generated by Mailtrap
      }
    });

    const mailOptions = {
      from: "no-reply@4-playersofcolorado.org",
      ...emailData,
      html: getTransactionalTemplate(
        emailData.preheader || emailData.subject,
        emailData.subject,
        emailData.html
      )
    };

    return transport.sendMail(mailOptions, (error, info) => {
      if (error) {
        throw new Error(error);
      }

      const msg = "Message sent";
      console.log(`${msg}: ${info.messageId}`);
      return Promise.resolve(msg);
    });
  }
};

module.exports.sendTransactionalEmail = sendTransactionalEmail;
